import type { Metadata } from 'next';
import { Outfit, Space_Grotesk } from 'next/font/google';
import './globals.scss';

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

const space_grotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.style} ${space_grotesk.variable}`}>
        {children}
      </body>
    </html>
  );
}
